### ISSUE TITLE
Database host to paramaters.yml

### ISSUE THREAD

**Issue by Glideh** [eko/docker-symfony#1]
Would it be worth talking about the `parameters.yml` where we can configure:

```yml
parameters:
#...
    database_host: db
#...
```

Because the linked containers are aliased in `/etc/hosts`.
It took me ~2h to figure this out...
