### ISSUE TITLE
PHP service "expose" should be "ports"

### ISSUE THREAD

**Issue by ypereirareis** [eko/docker-symfony#17]
``` yaml
php:
    build: php-fpm
    expose:
        - 9000:9000
```

``` yaml
php:
    build: php-fpm
    ports:
        - 9000:9000
```
