### ISSUE TITLE
Symfony 4 connection refused

### ISSUE THREAD

**Issue by norbertogomez** [eko/docker-symfony#83]
While trying to run: 
`docker-compose run php bin/console doctrine:migrations:diff`

I get the error:
```
In AbstractMySQLDriver.php line 112:
                                                                              
  An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused  
                                                                              

In PDOConnection.php line 50:
                                             
  SQLSTATE[HY000] [2002] Connection refused  
                                             

In PDOConnection.php line 46:
                                             
  SQLSTATE[HY000] [2002] Connection refused 
```

This is my config at doctrine.yaml:
```
doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
```

My symfony .env `DATABASE_URL` variable looks like this:
`DATABASE_URL=mysql://root:root@127.0.0.1:3306/symfony` also tried with `DATABASE_URL=mysql://symfony:symfony@127.0.0.1:3306/symfony`

The extrange thing here is that I can enter using DBeaver using both ways to connect
I cleared cache, rebuild/restarted containers...

¿Did I forgot something?

**Comment by ingmarkleine** [comment]
same for me. internet didn't supply me any answers at this time

**Comment by ingmarkleine** [comment]
Correct me if i am wrong

config/services.yaml:
```
parameters:
    locale: 'en'
    DATABASE_HOST: db
    DATABASE_USER: root
    DATABASE_PASSWORD:
```
config/packages/doctrine.yaml
```
parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): 'mysql://root:@db:3306/sophie'
    database_user: root
    database_password: root
```

and .env:

```
DATABASE_URL=mysql://root:root@db:3306/my_database
```
so **db** is necassary
