### ISSUE TITLE
Typo in path??

### ISSUE THREAD

**Issue by chucky2305** [eko/docker-symfony#94]
Is there a typo in the path? I added "comments" in the code examples

docker-compose.yml
```
elk:
        image: willdurand/elk
        ports:
            - "81:80"
        volumes:
            // Either this has to be /var/www/symfony/var/log 
            - ./logs/symfony:/var/www/symfony/var/logs:cached
```

logstash.conf
```
input {
  file {
    type => "nginx_access"
    path => "/var/log/nginx/symfony_access.log"
    start_position => beginning
  }
  file {
    type => "symfony_dev"
   // or this has to be /var/www/symfony/var/logs/dev.log
    path => "/var/www/symfony/var/log/dev.log"
    start_position => beginning
  }
  file {
    type => "symfony_prod"
    path => "/var/www/symfony/var/log/prod.log"
    start_position => beginning
  }
}
```
